import { makeStyles } from "tss-react/mui";
import { alpha } from "@mui/material/styles";

export const useStyles = makeStyles()((theme) => ({
  cardRoot: {
    display: "flex",
    flexDirection: "column",
    width: "280px",
    flexShrink: 0,
    backgroundColor: theme.palette.background.paper,
    borderRadius: theme.shape.borderRadius,
    boxShadow: theme.shadows[2],
    overflow: "hidden",
    transition: "transform 0.2s ease-in-out, box-shadow 0.2s ease-in-out",
    "&:hover": {
      transform: "translateY(-4px)",
      boxShadow: theme.shadows[6],
    },
    cursor: "default",
  },
  imageContainer: {
    width: "100%",
    height: "180px",
    backgroundColor: alpha(theme.palette.text.disabled, 0.1),
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  image: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
  },
  contentArea: {
    padding: theme.spacing(2),
    display: "flex",
    flexDirection: "column",
    flexGrow: 1,
    gap: theme.spacing(1),
  },
  name: {
    fontWeight: 700,
    fontSize: "1.2rem",
    color: theme.palette.text.primary,
    lineHeight: 1.3,
    minHeight: "2.6em",
    overflow: "hidden",
    textOverflow: "ellipsis",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
  },
  description: {
    fontSize: "0.875rem",
    color: theme.palette.text.secondary,
    flexGrow: 1,
    minHeight: "3.9em",
    overflow: "hidden",
    textOverflow: "ellipsis",
    display: "-webkit-box",
    WebkitLineClamp: 3,
    WebkitBoxOrient: "vertical",
    marginBottom: theme.spacing(1),
  },
  priceAndActionContainer: {
    marginTop: "auto",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: theme.spacing(1),
  },
  price: {
    fontWeight: "bold",
    color: theme.palette.primary.light,
    fontSize: "1.1rem",
  },
  addToCartButton: {},
}));
